default:
  db_path: "db/jobs.sqlite3"
  table_name: "jobs_data"

sites:
  # REMOVED careerjet: Cloudflare-protected site, requires advanced bot bypass
  # REMOVED opensareer: Site does not exist or is unreachable
  
  brighter_monday:
    base_url: "https://www.brightermonday.co.ke"
    listing_path: "/jobs?page={page}"
    listing_selector: "a[href*='/listings/'][title]"
    title_attribute: "title"
    content_selector: "article.job__details"
    pagination_selector: "ul.pagination a[href*='?page=']"
    
  jobwebkenya:
    base_url: "https://www.jobwebkenya.com"
    listing_path: "/jobs/page/{page}"
    listing_selector: "li.job a"
    title_attribute: null       # use .text instead
    content_selector: "div.section.single"
    pagination_selector: "ul.pagination li a[href*='/jobs/page/']"
    
  myjobmag:
    base_url: "https://www.myjobmag.co.ke"
    listing_path: "/jobs/page/{page}"
    listing_selector: "li.mag-b a"
    title_attribute: null
    content_selector: "li#printable"
    pagination_selector: "ul.pagination li a[href*='/jobs/page/']"
